version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  identity:
    build:
      context: .
      dockerfile: /backend/src/Identity/Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BUILD_CONFIGURATION=Debug
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    ports:
      - 5001:80
    command: dotnet run --no-build --no-launch-profile --urls http://0.0.0.0:80

  api:
    build:
      context: .
      dockerfile: backend/src/API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5002:5003
    command: dotnet run --no-launch-profile -c Debug --urls http://0.0.0.0:5003

  client:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 4200:80
    command: npm start -- --host 0.0.0.0 --disable-host-check --poll 1 --port 80
